# Generated by Django 3.2.9 on 2021-12-15 19:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
import orderInventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('modifyAt', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('modifyAt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defaultValue', models.FloatField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('modifyAt', models.DateTimeField(blank=True, default=None, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, default=None, null=True)),
                ('ingredientId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredientName', to='orderInventory.ingredientindividual')),
                ('itemId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemName', to='orderInventory.itemindividual')),
            ],
        ),
        migrations.CreateModel(
            name='OrderIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Name of Function For Which this order is Placed')),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('deliveredAt', models.DateTimeField(blank=True, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('emailAddress', models.EmailField(max_length=254, unique=True)),
                ('mobileNumber', models.CharField(max_length=15, validators=[orderInventory.models.checkMobileNumber])),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('itemId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ItemName', to='orderInventory.items', verbose_name='Items With Ingredient Which need to Order')),
                ('orderId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderName', to='orderInventory.orderindividual', verbose_name='To track Order')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientindividual',
            name='orderAt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OrderStore', to='orderInventory.store'),
        ),
    ]
