# Generated by Django 3.2.9 on 2021-12-22 17:25

from django.db import migrations, models
import orderInventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('orderInventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderindividual',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='orderindividual',
            name='mobileNumber',
            field=models.CharField(default=1234567890, max_length=15, validators=[orderInventory.models.checkMobileNumber]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderindividual',
            name='numberOfPerson',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
