# Generated by Django 3.2.9 on 2021-12-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderInventory', '0002_auto_20211222_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderindividual',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
