# Generated by Django 3.2.9 on 2022-01-02 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderInventory', '0003_orderindividual_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='ingredientId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientName', to='orderInventory.ingredientindividual'),
        ),
        migrations.AlterField(
            model_name='items',
            name='itemId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemName', to='orderInventory.itemindividual'),
        ),
    ]
