# Generated by Django 3.2.9 on 2022-01-04 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderInventory', '0004_auto_20220102_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderName', to='orderInventory.orderindividual', verbose_name='To track Order'),
        ),
    ]
