# Generated by Django 3.2.9 on 2022-01-09 08:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderInventory', '0005_alter_order_orderid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='orderindividual',
            old_name='deliveredAt',
            new_name='deliveryDate',
        ),
        migrations.RemoveField(
            model_name='ingredientindividual',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='ingredientindividual',
            name='modifyAt',
        ),
        migrations.RemoveField(
            model_name='ingredientindividual',
            name='orderAt',
        ),
        migrations.RemoveField(
            model_name='items',
            name='defaultValue',
        ),
        migrations.RemoveField(
            model_name='order',
            name='itemId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='order',
            name='deletedAt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='modifyAt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='orderItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ItemName', to='orderInventory.items', verbose_name='Items With Ingredient Which need to Order'),
        ),
        migrations.AddField(
            model_name='orderindividual',
            name='modifyAt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='ingredientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientName', to='orderInventory.ingredientindividual'),
        ),
        migrations.AlterField(
            model_name='items',
            name='itemId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itemName', to='orderInventory.itemindividual'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='orderId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orderName', to='orderInventory.orderindividual', verbose_name='To track Order'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.AddField(
            model_name='ingredientindividual',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='orderInventory.category'),
        ),
    ]
