# Generated by Django 3.2.9 on 2022-02-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderInventory', '0007_alter_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32, unique=True)),
            ],
        ),
    ]
