# Generated by Django 3.2.9 on 2022-03-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderInventory', '0009_itemindividual_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemindividual',
            name='confirmItem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderindividual',
            name='confirmOrder',
            field=models.BooleanField(default=False),
        ),
    ]
